#include "captive_portal.h"
#include <stddef.h>
static const char PORTAL_HTML[] =
    "<!DOCTYPE html>\n<html lang=\"en\"><head>\n<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n<title>Thread Hub Setup</title>\n<style>\n:root{--bg:#070b14;--bg2:#0d1526;--card:rgba(18,28,48,.92);--line:rgba(120,160,220,.14);\n--text:#eef3ff;--muted:#8b9cb8;--accent:#5b8cff;--accent2:#7c5cff;--ok:#34d399;--danger:#f87171;\n--glow:0 0 60px rgba(91,14"
    "0,255,.18)}\n*{box-sizing:border-box}html,body{height:100%;margin:0}\nbody{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;\ncolor:var(--text);background:radial-gradient(1200px 600px at 10% -10%,#1a2a55 0%,transparent 55%),\nradial-gradient(900px 500px at 100% 0%,#2a1850 0%,transparent 50%),var(--bg);min-height:100%}\n.wrap{max-width:480px;margin:0 auto;padd"
    "ing:2rem 1.1rem 3rem}\n.brand{display:flex;align-items:center;gap:.75rem;margin-bottom:1.5rem}\n.logo{width:42px;height:42px;border-radius:12px;background:linear-gradient(135deg,var(--accent),var(--accent2));\ndisplay:grid;place-items:center;box-shadow:var(--glow);font-weight:800}\n.brand h1{font-size:1.2rem;margin:0;letter-spacing:-.02em}\n.brand p{margin:.15rem 0 0;color:var(--muted);font-size:.82rem"
    "}\n.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:1.25rem 1.2rem;\nbackdrop-filter:blur(12px);box-shadow:0 20px 50px rgba(0,0,0,.35)}\n.card h2{margin:0 0 .35rem;font-size:1.05rem}\n.lead{color:var(--muted);font-size:.88rem;line-height:1.45;margin:0 0 1.1rem}\nlabel{display:block;font-size:.75rem;color:var(--muted);margin:.7rem 0 .3rem;font-weight:600;letter-spacin"
    "g:.02em;text-transform:uppercase}\ninput,select{width:100%;padding:.7rem .8rem;border-radius:12px;border:1px solid var(--line);\nbackground:rgba(7,11,20,.75);color:var(--text);font-size:.95rem;outline:none;transition:border .15s,box-shadow .15s}\ninput:focus{border-color:rgba(91,140,255,.55);box-shadow:0 0 0 3px rgba(91,140,255,.15)}\n.row{display:grid;grid-template-columns:1fr 1fr;gap:.65rem}\n.hint{f"
    "ont-size:.78rem;color:var(--muted);margin:.35rem 0 0}\n.actions{display:flex;gap:.6rem;margin-top:1.2rem;flex-wrap:wrap}\nbutton{border:0;border-radius:12px;padding:.75rem 1.1rem;font-weight:700;cursor:pointer;font-size:.92rem}\n.btn{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;box-shadow:0 8px 24px rgba(91,140,255,.28);flex:1}\n.btn:disabled{opacity:.55;cursor:not-allowe"
    "d}\n.btn2{background:rgba(255,255,255,.06);color:var(--text);border:1px solid var(--line)}\n.toast{margin-top:1rem;padding:.75rem .9rem;border-radius:12px;display:none;font-size:.88rem}\n.toast.ok{display:block;background:rgba(52,211,153,.12);color:var(--ok);border:1px solid rgba(52,211,153,.25)}\n.toast.err{display:block;background:rgba(248,113,113,.12);color:var(--danger);border:1px solid rgba(248,1"
    "13,113,.25)}\n.sec{margin-top:1.1rem;padding-top:1rem;border-top:1px solid var(--line)}\n.pill{display:inline-flex;align-items:center;gap:.35rem;padding:.2rem .55rem;border-radius:999px;font-size:.72rem;\nbackground:rgba(91,140,255,.12);color:#b9cdff;border:1px solid rgba(91,140,255,.22)}\nfooter{margin-top:1.5rem;text-align:center;color:var(--muted);font-size:.75rem}\n</style></head>\n<body><div class="
    "\"wrap\">\n  <div class=\"brand\">\n    <div class=\"logo\">TH</div>\n    <div>\n      <h1>Thread Hub</h1>\n      <p>First-time setup · Captive portal</p>\n    </div>\n  </div>\n  <div class=\"card\">\n    <div style=\"display:flex;justify-content:space-between;align-items:center;gap:.5rem;margin-bottom:.4rem\">\n      <h2>Connect your hub</h2>\n      <span class=\"pill\">Setup mode</span>\n    </div>\n    <p class=\"lead"
    "\">Join this device to your home Wi‑Fi and point it at your MQTT broker (Node‑RED / Mosquitto).</p>\n\n    <form id=\"f\" onsubmit=\"return save(event)\">\n      <label>Wi‑Fi network (SSID)</label>\n      <input id=\"wifi_ssid\" name=\"wifi_ssid\" required maxlength=\"32\" placeholder=\"HomeWiFi\" autocomplete=\"off\">\n\n      <label>Wi‑Fi password</label>\n      <input id=\"wifi_pass\" name=\"wifi_pass\" type=\"pa"
    "ssword\" maxlength=\"64\" placeholder=\"Leave empty if open\" autocomplete=\"new-password\">\n\n      <div class=\"sec\">\n        <h2 style=\"font-size:.95rem;margin:0 0 .4rem\">MQTT broker</h2>\n        <p class=\"lead\" style=\"margin-bottom:.4rem\">Usually your always-on IoT PC or NAS on the LAN.</p>\n        <label>Broker host / IP</label>\n        <input id=\"mqtt_host\" name=\"mqtt_host\" required maxlength=\"63\" pl"
    "aceholder=\"192.168.1.50\" inputmode=\"decimal\">\n        <div class=\"row\">\n          <div>\n            <label>Port</label>\n            <input id=\"mqtt_port\" name=\"mqtt_port\" type=\"number\" min=\"1\" max=\"65535\" value=\"1883\">\n          </div>\n          <div>\n            <label>Topic base</label>\n            <input id=\"topic_base\" name=\"topic_base\" maxlength=\"15\" value=\"home\" placeholder=\"home\">\n         "
    " </div>\n        </div>\n        <label>MQTT username <span style=\"opacity:.7\">(optional)</span></label>\n        <input id=\"mqtt_user\" name=\"mqtt_user\" maxlength=\"31\" autocomplete=\"off\">\n        <label>MQTT password <span style=\"opacity:.7\">(optional)</span></label>\n        <input id=\"mqtt_pass\" name=\"mqtt_pass\" type=\"password\" maxlength=\"64\" autocomplete=\"new-password\">\n        <label>Hostname</lab"
    "el>\n        <input id=\"hostname\" name=\"hostname\" maxlength=\"31\" value=\"thread-hub\">\n        <p class=\"hint\">After saving, the hub reboots and joins your Wi‑Fi. Open the dashboard at the new IP (check serial log or your router).</p>\n      </div>\n\n      <div class=\"actions\">\n        <button class=\"btn\" id=\"btn\" type=\"submit\">Save &amp; reboot</button>\n      </div>\n      <div id=\"toast\" class=\"toas"
    "t\"></div>\n    </form>\n  </div>\n  <footer>Thread ESP32 Border Gateway · local setup only</footer>\n</div>\n<script>\nasync function boot(){\n  try{\n    const r=await fetch('/api/settings'); const s=await r.json();\n    if(s.wifi_ssid) wifi_ssid.value=s.wifi_ssid;\n    if(s.mqtt_host) mqtt_host.value=s.mqtt_host;\n    if(s.mqtt_port) mqtt_port.value=s.mqtt_port;\n    if(s.topic_base) topic_base.value=s.top"
    "ic_base;\n    if(s.mqtt_user) mqtt_user.value=s.mqtt_user;\n    if(s.hostname) hostname.value=s.hostname;\n  }catch(e){}\n}\nasync function save(ev){\n  ev.preventDefault();\n  const btn=document.getElementById('btn');\n  const toast=document.getElementById('toast');\n  btn.disabled=true; toast.className='toast'; toast.textContent='';\n  const body={\n    wifi_ssid:wifi_ssid.value.trim(),\n    wifi_pass:wifi_"
    "pass.value,\n    mqtt_host:mqtt_host.value.trim(),\n    mqtt_port:Number(mqtt_port.value||1883),\n    mqtt_user:mqtt_user.value.trim(),\n    mqtt_pass:mqtt_pass.value,\n    topic_base:(topic_base.value||'home').trim(),\n    hostname:(hostname.value||'thread-hub').trim()\n  };\n  try{\n    const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body"
    ")});\n    const j=await r.json();\n    if(!j.ok){ throw new Error(j.error||'save failed'); }\n    toast.className='toast ok';\n    toast.textContent='Saved. Rebooting… reconnect your phone to home Wi‑Fi, then open the hub IP.';\n    setTimeout(()=>fetch('/api/reboot',{method:'POST'}).catch(()=>{}), 700);\n  }catch(e){\n    toast.className='toast err'; toast.textContent=String(e.message||e);\n    btn.d"
    "isabled=false;\n  }\n  return false;\n}\nboot();\n</script>\n</body></html>";
const char *captive_portal_html(void) { return PORTAL_HTML; }
size_t captive_portal_html_len(void) { return sizeof(PORTAL_HTML) - 1; }