; ESP32-H2 temperature & humidity Thread end device
[platformio]
src_dir = src
include_dir = include
default_envs = esp32h2

[env:esp32h2]
platform = espressif32
board = esp32-h2-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_upload.flash_size = 4MB
build_flags =
    -DSENSOR_TYPE_TEMP_HUM=1
    -Iinclude
    -I../shared/protocol
monitor_filters = esp32_exception_decoder, colorize
upload_speed = 921600
